### ISSUE TITLE
Issues on My-Portfolio project 

### ISSUE THREAD

**Issue by KIsmoilov** [mrbhi/My-Portfolio#5]
Could you please fix the following issues in order to make your portfolio better looking?

- Please make the background image of the cards repeat property to "no-repeat"
- Please apply max-width to the cards
- Please make the font size of the form input fields similar and re-sizing (resize: none) of the text area should not be allowed
- Please work on the margin-top of the h1 element on the first page and use the following **calc(100vh - 72px)**

**Comment by mrbhi** [comment]
Issues Resolved.

Thanks for notifying me. I appreciate that.
